/**
 * Shared footer — umetni na sve stranice.
 * HTML stranica treba imati: <div id="site-footer"></div>
 */
(function () {
  var el = document.getElementById('site-footer');
  if (!el) return;

  el.outerHTML = [
    '<footer class="footer" aria-label="Footer">',
    '  <div class="container">',
    '    <div class="footer-grid">',
    '',
    '      <div class="footer-brand">',
    '        <div class="nav-logo" style="margin-bottom:16px">',
    '          <img src="images/import_cars_usa.jpg" alt="Importcarsusa" class="logo-img">',
    '        </div>',
    '        <p class="footer-desc">',
    '          Vaš pouzdani partner za uvoz kvalitetnih automobila iz Amerike.',
    '          Chicago &rarr; Banja Luka &middot; Transparentno i po najboljoj cijeni.',
    '        </p>',
    '        <div class="social-links">',
    '          <a href="https://www.facebook.com/mamotorslnc/" class="social-link"',
    '             target="_blank" rel="noopener noreferrer" aria-label="Pratite nas na Facebooku">',
    '            <svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">',
    '              <path d="M18 2h-3a5 5 0 00-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 011-1h3z"/>',
    '            </svg>',
    '          </a>',
    '        </div>',
    '      </div>',
    '',
    '      <div class="footer-col">',
    '        <h4>Brze Veze</h4>',
    '        <ul class="footer-links">',
    '          <li><a href="index.html"      class="footer-link">&rsaquo; Naslovna</a></li>',
    '          <li><a href="about.html"      class="footer-link">&rsaquo; O Nama</a></li>',
    '          <li><a href="inventory.html"  class="footer-link">&rsaquo; Vozila</a></li>',
    '          <li><a href="kalkulator.html" class="footer-link">&rsaquo; Kalkulator</a></li>',
    '          <li><a href="contact.html"    class="footer-link">&rsaquo; Kontakt</a></li>',
    '        </ul>',
    '      </div>',
    '',
    '      <div class="footer-col">',
    '        <h4>Radno Vrijeme</h4>',
    '        <div class="footer-hours">',
    '          <div class="footer-hour-row"><span>Pon&ndash;Sub</span><span>9:00 &ndash; 17:00</span></div>',
    '          <div class="footer-hour-row"><span>Nedjelja</span><span class="closed-text">Zatvoreno</span></div>',
    '        </div>',
    '      </div>',
    '',
    '      <div class="footer-col">',
    '        <h4>Kontakt</h4>',
    '        <ul class="footer-links">',
    '          <li>',
    '            <a href="https://maps.google.com/?q=Ulica+Cara+Dušana+bb,+Kotor+Varoš,+Bosnia" class="footer-link"',
    '               target="_blank" rel="noopener noreferrer">',
    '              &rsaquo; Ulica Cara Dušana bb, Kotor Varoš, Banja Luka,<br>&nbsp;&nbsp;Republika Srpska, BiH',
    '            </a>',
    '          </li>',
    '          <li><a href="tel:+38765329696" class="footer-link">&rsaquo; +387 65 329 696</a></li>',
    '        </ul>',
    '      </div>',
    '',
    '    </div>',
    '    <div class="footer-bottom">',
    '      <span>&copy; 2026 Importcarsusa. Sva prava zadržana.</span>',
    '      <span>Banja Luka, Republika Srpska, BiH</span>',
    '    </div>',
    '  </div>',
    '</footer>'
  ].join('\n');
})();
